---
- name: install kafka.service...
  become: yes
  become_user: root
  with_items:
    - f: kafka.service
      d: /etc/systemd/system
      m: '0644'
  register: kafka_service_installed
  template:
    src: '{{item}}.j2'
    dest: '{{item.d}}/{{item.f}}'
    mode: '{{item.m}}'

- name: systemctl daemon-reload
  become: yes
  become_user: root
  when: kafka_service_installed|changed and kafka_launch
  command: systemctl daemon-reload

- name: launch kafka...
  become: yes
  become_user: root
  when: kafka_launch
  service:
    name: kafka
    enabled: yes
    state: started
  
